# Generated by Django 3.0.8 on 2020-07-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
